Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2024
Var
n1, n2, M: Real

Inicio
Escreval ("Faça a média aritmética de dois números")
Leia (n1, n2)
M <- ((n1+n2) / 2)
Escreva ("A média é ", M)


Fimalgoritmo