Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2024
Var
n1, n2, S: real

Inicio
Escreval ("Escreva dois números para multiplicação")
Leia (n1, n2)
S <- (n1 * n2)
Escreva ("A multiplicação é ", S)


Fimalgoritmo