Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Soma de Dois Números
// Autor(a)    : Angel
// Data atual  : 23/02/2024
Var
N1, N2: inteiro
M: Real
Inicio
      Escreva ("Informe um número: ")
               Leia (N1)
      Escreva ("Segundo numero:")
               Leia (N2)
      M <- (N1 + N2) / 2
      Escreva ("A média entre ", N1, "e  ", N2, "é ", M)


Fimalgoritmo